name = "kubectl"
type = "cli"

[platform.linux]
download-file = "linux/{arch}/kubectl"
# checksum_file = "linux/{arch}/kubectl.sha256"

[platform.macos]
download-file = "darwin/{arch}/kubectl"
# checksum_file = "darwin/{arch}/kubectl.sha256"

[platform.windows]
download-file = "windows/{arch}/kubectl.exe"
# checksum_file = "windows/{arch}/kubectl.sha256"

[install]
download-url = "https://dl.k8s.io/release/v{version}/bin/{download_file}"
# checksum-url = "https://dl.k8s.io/release/v{version}/bin/{checksum_file}"
unpack = false

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/kubernetes/kubectl"
git-tag-pattern = "^(?:v|kubernetes-)(.*)$"
